branches:
  - main

repositoryUrl: 'git@github.com:okp4/follow-contributor-action.git'

plugins:
  - - '@semantic-release/commit-analyzer'
    - preset: conventionalcommits
  - - "@semantic-release/release-notes-generator"
    - preset: conventionalcommits
  - - '@semantic-release/changelog'
    - changelogFile: CHANGELOG.md
      changelogTitle: '# Follow contributor action'
  - - '@semantic-release/npm'
    - npmPublish: false
  - - "@semantic-release/github"
  - - '@semantic-release/git'
    - assets:
        - CHANGELOG.md
        - dist/
        - package.json
      message: 'chore(release): perform release ${nextRelease.version}'
